
#PersistentStaticVolume

apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-static
spec:
   capacity:
     storage: 1Gi
   accessModes: 
     - ReadWriteOnce  
   storageClassName: slow
   #gcePersistentDisk:
   awsElasticBlockStore:
      pdName: my-data-disk
      fsType: ext4
