apiVersion: v1
kind: Pod
metadata:
   name: redis
spec:
   containers:
   - name: redis
     image: k8s.gcr.io/redis
     volumeMounts:
     - mountPath: /redis-master
       name: config

   volumes:
     - name: config
       configMap:
         name: example-redis-config
         items:
         - key: redis-config
           path: redis.conf
