apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-green-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
        version: "1.11"
    spec:
      containers: 
        - name: nginx
          image: nginx:1.11
          ports:
            - name: http
              containerPort: 80
